// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucyjwpmssujaakjxwopw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjeWp3cG1zc3VqYWFranh3b3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NDQ3MjYsImV4cCI6MjA5NTAyMDcyNn0.WXZqyqN9LTw2EjsY3mAkLifzri9t54NNBZhFDNDkR8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);